### PR TITLE
OSX support

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maclandrol** [comment]
More precisely, are   `'libRDKitChemReactions'` and `'libRDKitChemTransforms'` found and linked on linux ?

**Comment by hadim** [comment]
In the `CMakeCache.txt` of the rdchiral lib on linux I can indeed find `libRDKitChemReactions` but **not** `libRDKitChemTransforms`.

**Comment by hadim** [comment]
I also checked and they are both available in the osx and linux conda packages.

**Comment by hadim** [comment]
Conpilation and linking works but test fails now when importing rdchiral. It seems like the package is corrupted. Try to apply my last commit locally maybe.

**Pull request merged**
