### PR TITLE
Update to version 1.1.3 and rdkit 2022.03, 2022.09

### PR DESCRIPTION
**Pull request by ljn917**
Updated with only rdkit 2021.09, 2022.03, 2022.09

### CODE REVIEW

**Comment by hadim** [comment]
For any CI failing because of this kind of error:

```bash
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - rdkit 2021.09.*
 - pip
 - python 3.10.* *_cpython
 - boost >=1.67
 - python
 - boost-cpp >=1.67

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package rdkit-2021.09.1-py37h9710f2f_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed
- 
```

you should exclude them in the recipe using the `skip: true` selector.

**Comment by hadim** [comment]
@ljn917 do you want to keep building for rdkit 2021.09? Or do you think we can just remove it and keep only the latest two versions of rdkit?

**Comment by ljn917** [comment]
@hadim I think we can remove rdkit 2021.09 because it has been built for 1.1.2 before. There is really no real changes between 1.1.2 and 1.1.3, and people are request python 3.10 which 2021.09 does not support.

**Comment by hadim** [comment]
LGTM for me @ljn917, ping me if ready to merge on your side.

Do you want to be added as a maintainer?

**Comment by ljn917** [comment]
@hadim It is good to me too. Glad to co-maintain this package.

**Comment by hadim** [comment]
Thanks!

**Pull request merged**
